# Generated by Django 5.0.14 on 2026-06-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='earnings/screenshots/')),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trips', models.PositiveIntegerField(default=0)),
                ('earnings_date', models.DateField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing OCR'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ocr_raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_uploads', to='drivers.driver')),
            ],
        ),
    ]
