# Generated by Django 5.0.14 on 2026-06-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel / CNG'), ('REPAIR', 'Repair & Maintenance'), ('CAR_WASH', 'Car Wash'), ('PARKING', 'Parking'), ('TYRE', 'Tyre Service'), ('MISCELLANEOUS', 'Miscellaneous')], default='MISCELLANEOUS', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expense_date', models.DateField()),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('ocr_status', models.CharField(choices=[('NONE', 'No OCR Required'), ('PENDING', 'Pending OCR'), ('PROCESSING', 'Processing OCR'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NONE', max_length=20)),
                ('ocr_raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cars.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='drivers.driver')),
            ],
        ),
    ]
