# Generated by Django 5.0.14 on 2026-06-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LICENSE', 'Driver License'), ('AADHAAR', 'Aadhaar Card'), ('INSURANCE', 'Vehicle Insurance'), ('PERMIT', 'Vehicle Permit'), ('FITNESS', 'Fitness Certificate'), ('POLLUTION', 'Pollution Certificate'), ('OTHER', 'Other Document')], max_length=30)),
                ('document_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('document_file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cars.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
            ],
        ),
    ]
