# Generated by Django 5.0.14 on 2026-06-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expenses_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advances_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('manual_adjustment_reason', models.TextField(blank=True, null=True)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='drivers.driver')),
            ],
        ),
    ]
